# ~/.config/starship.toml

# Define the prompt order
format = """
$all
$right_prompt
"""

# Configure the right prompt
[right_prompt]
format = """
$git_branch$git_commit$git_state$git_status
"""

# Configure the Git modules as needed
[git_branch]
format = "[$branch]($style) "

[git_commit]
format = "[$hash]($style) "

[git_state]
format = '([$state( $progress_current/$progress_total)])($style) '

[git_status]
format = '([\[$all_status$ahead_behind\]]($style)) '
